// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconCustomCoffee: typeof import('~icons/custom/coffee')['default']
    IconCustomVueLogo: typeof import('~icons/custom/vue-logo')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconLocalVueLogo: typeof import('~icons/local/vue-logo')['default']
    IconMdiAlphaX: typeof import('~icons/mdi/alpha-x')['default']
    IconMyCustomVueLogo: typeof import('~icons/my-custom/vue-logo')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ILocalCoffee: typeof import('~icons/local/coffee')['default']
    ILocalLogo: typeof import('~icons/local/logo')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    IMdiAlphaX: typeof import('~icons/mdi/alpha-x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
